#title in header
title: "Zack's blog"

#main info
#owner
owner: ""
email: zaaack@qq.com
info: ""
#description
desc: ""

#menu
menu:
  é¡¹ç›®: /projects
  å·¥å…·: /tools
  å½’æ¡£: /archives
  å…³äº: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/zaaack
weibo: "http://weibo.com/2835064591"
douban: "https://www.douban.com/people/67599254/"

# Misc
nanobar: /js/nanobar.min.js
switch_light: â˜€ï¸
switch_dark: ğŸŒ‘

# favicon
favicon: /avatar.png
# thumbnail
thumbnail: /avatar.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
